version: "3"

services:

  matchbox:
    image: quay.io/coreos/matchbox:latest
    container_name: matchbox
    network_mode: "host"
    volumes:
      - './volumes/var/lib/matbox:/var/lib/matchbox'
      - './volumes/etc/matchbox:/etc/matchbox:ro'
    command: "-address=0.0.0.0:8080 -rpc-address=0.0.0.0:8081 -log-level=debug"



  dnsmasq:
    image: quay.io/coreos/dnsmasq
    container_name: dnsmasq
    network_mode: "host"
    command: >
        -d -q
        --dhcp-range=192.168.168.1,proxy,255.255.255.0
        --enable-tftp --tftp-root=/var/lib/tftpboot
        --dhcp-userclass=set:ipxe,iPXE
        --pxe-service=tag:#ipxe,x86PC,"PXE chainload to iPXE",undionly.kpxe
        --pxe-service=tag:ipxe,x86PC,"iPXE",http://matchbox.home:8080/boot.ipxe
        --log-queries
        --log-dhcp
